-- Create strains table
CREATE TABLE IF NOT EXISTS public.strains (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL CHECK (type IN ('indica', 'sativa', 'hybrid', 'auto')),
  thc_range TEXT,
  cbd_range TEXT,
  flowering_days_min INTEGER,
  flowering_days_max INTEGER,
  difficulty TEXT CHECK (difficulty IN ('easy', 'medium', 'hard')),
  yield_indoor TEXT,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.strains ENABLE ROW LEVEL SECURITY;

-- Everyone can read strains
CREATE POLICY "Anyone can read strains" ON public.strains FOR SELECT USING (true);

-- Only service role can insert/update
CREATE POLICY "Service role can manage strains" ON public.strains FOR ALL USING (auth.role() = 'service_role');

-- Index for search
CREATE INDEX IF NOT EXISTS idx_strains_name ON public.strains (lower(name));
CREATE INDEX IF NOT EXISTS idx_strains_type ON public.strains (type);

-- Seed data
INSERT INTO public.strains (name, type, thc_range, cbd_range, flowering_days_min, flowering_days_max, difficulty, yield_indoor, description) VALUES
('OG Kush', 'hybrid', '20-26%', '0.1-0.3%', 56, 65, 'medium', '400-500 g/m²', 'Leyenda californiana con aroma terroso y cítrico. Produce efectos potentes y relajantes, considerada la madre de muchas cepas modernas.'),
('White Widow', 'hybrid', '18-25%', '0.1-0.2%', 56, 63, 'easy', '450-500 g/m²', 'Clásica holandesa famosa por su gruesa capa de tricomas blancos. Equilibrio perfecto entre euforia cerebral y relajación corporal.'),
('Blue Dream', 'hybrid', '17-24%', '0.1-0.2%', 60, 70, 'easy', '500-600 g/m²', 'Híbrido californiano cruce de Blueberry y Haze. Sabor dulce a arándano con efecto cerebral motivador y relajación suave.'),
('Sour Diesel', 'sativa', '19-25%', '0.1-0.3%', 70, 84, 'hard', '400-500 g/m²', 'Sativa legendaria con fuerte aroma a diésel y cítricos. Efecto energizante y cerebral ideal para el día, floración más larga.'),
('Northern Lights', 'indica', '16-21%', '0.1-0.3%', 45, 55, 'easy', '450-550 g/m²', 'Una de las índicas más puras y famosas del mundo. Floración rápida, poco olor y efecto relajante profundo. Ideal para principiantes.'),
('AK-47', 'hybrid', '17-22%', '0.1-0.7%', 56, 65, 'easy', '350-500 g/m²', 'Ganadora de múltiples Cannabis Cup. Mezcla de genéticas colombianas, mexicanas, tailandesas y afganas con efecto largo y relajante.'),
('Jack Herer', 'sativa', '18-24%', '0.1-0.2%', 60, 70, 'medium', '400-500 g/m²', 'Nombrada en honor al activista cannábico. Combinación de Haze, Northern Lights y Skunk con efecto creativo y eufórico.'),
('Girl Scout Cookies (GSC)', 'hybrid', '25-28%', '0.1-0.2%', 60, 70, 'hard', '300-400 g/m²', 'Cepa premium de San Francisco con sabor dulce y terroso. THC muy alto con efecto potente que combina euforia y relajación profunda.'),
('Gelato', 'hybrid', '20-25%', '0.1-0.2%', 56, 65, 'medium', '400-500 g/m²', 'Cruce de Sunset Sherbet y Thin Mint GSC. Sabor cremoso a helado con colores púrpura intensos y efecto equilibrado poderoso.'),
('Runtz', 'hybrid', '19-29%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Zkittlez y Gelato, famosa por su sabor dulce a caramelo frutal. Cogollos densos y coloridos con efecto eufórico y relajante.'),
('Wedding Cake', 'hybrid', '22-27%', '0.1-0.2%', 56, 65, 'medium', '450-550 g/m²', 'Fenotipo de Triangle Mints con sabor a vainilla y masa dulce. Alta producción de resina y potencia, ideal para extracciones.'),
('Gorilla Glue #4 (GG4)', 'hybrid', '25-30%', '0.1-0.2%', 56, 63, 'medium', '450-550 g/m²', 'Famosa por su producción masiva de resina pegajosa. Aroma terroso y pino con efecto potente y sedante. Ganadora de múltiples copas.'),
('Amnesia Haze', 'sativa', '20-25%', '0.1-0.2%', 70, 84, 'hard', '500-600 g/m²', 'Sativa holandesa con genética Haze clásica. Aroma cítrico intenso y efecto cerebral potente y duradero. Requiere paciencia en floración.'),
('Skunk #1', 'hybrid', '15-20%', '0.1-0.3%', 49, 56, 'easy', '450-500 g/m²', 'Pilar fundamental de la genética moderna del cannabis. Aroma fuerte y penetrante con efecto alegre y energizante. Muy estable y fácil de cultivar.'),
('Purple Haze', 'sativa', '17-22%', '0.1-0.2%', 60, 70, 'medium', '350-450 g/m²', 'Inmortalizada por Jimi Hendrix. Tonos púrpura hermosos con sabor a bayas y efecto cerebral creativo y eufórico.'),
('Granddaddy Purple (GDP)', 'indica', '17-24%', '0.1-0.2%', 56, 70, 'medium', '400-450 g/m²', 'Índica californiana con colores púrpura intensos. Sabor a uva y bayas con efecto relajante profundo ideal para la noche.'),
('Bubba Kush', 'indica', '17-22%', '0.1-0.2%', 56, 63, 'easy', '350-450 g/m²', 'Índica clásica con sabor a café, chocolate y hashish. Planta compacta y robusta con efecto sedante y relajante muscular.'),
('Hindu Kush', 'indica', '15-20%', '0.1-0.3%', 49, 56, 'easy', '350-400 g/m²', 'Landrace pura de las montañas entre Pakistán y Afganistán. Aroma terroso a sándalo con alta producción de resina. Resistente y adaptable.'),
('Durban Poison', 'sativa', '15-25%', '0.1-0.2%', 56, 65, 'medium', '350-450 g/m²', 'Sativa pura originaria de Sudáfrica. Aroma dulce y anisado con efecto energizante y cerebral. Una de las pocas sativas landrace populares.'),
('Super Silver Haze', 'sativa', '18-23%', '0.1-0.2%', 63, 77, 'hard', '450-550 g/m²', 'Triple ganadora de la High Times Cannabis Cup. Cruce de Skunk, Northern Lights y Haze con efecto cerebral energético y duradero.'),
('Trainwreck', 'hybrid', '18-25%', '0.1-0.2%', 56, 65, 'medium', '400-500 g/m²', 'Híbrido potente con genética mexicana y tailandesa. Aroma a pino y limón con efecto cerebral intenso de inicio rápido.'),
('Cheese', 'hybrid', '15-20%', '0.1-0.3%', 56, 63, 'easy', '400-500 g/m²', 'Fenotipo británico de Skunk #1 con aroma inconfundible a queso fuerte. Efecto relajante y feliz, muy popular en Europa.'),
('Blueberry', 'indica', '17-24%', '0.1-0.2%', 56, 65, 'medium', '350-450 g/m²', 'Creada por DJ Short en los años 70. Famosa por su sabor dulce a arándano y colores azulados. Ganadora de la Cannabis Cup 2000.'),
('Pineapple Express', 'hybrid', '17-24%', '0.1-0.2%', 53, 63, 'easy', '450-550 g/m²', 'Cruce de Trainwreck y Hawaiian. Aroma tropical a piña y cedro con efecto energizante y creativo. Popularizada por la película homónima.'),
('Zkittlez', 'indica', '18-24%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Ganadora del Emerald Cup 2015. Sabor dulce frutal como caramelos con efecto relajante y alegre. Genética base de muchas cepas modernas.'),
('Do-Si-Dos', 'indica', '19-28%', '0.1-0.2%', 56, 65, 'medium', '400-500 g/m²', 'Cruce de Girl Scout Cookies y Face Off OG. Aroma floral y terroso con alta potencia. Cogollos densos cubiertos de tricomas.'),
('Mimosa', 'hybrid', '19-27%', '0.1-0.2%', 60, 68, 'medium', '450-550 g/m²', 'Cruce de Purple Punch y Clementine. Sabor cítrico dulce como el cóctel homónimo. Efecto elevador y energizante ideal para el día.'),
('Purple Punch', 'indica', '18-25%', '0.1-0.2%', 56, 63, 'easy', '450-550 g/m²', 'Cruce de Larry OG y Granddaddy Purple. Sabor a tarta de uva y arándano. Efecto sedante perfecto para el final del día.'),
('Sunset Sherbet', 'hybrid', '18-24%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Descendiente de Girl Scout Cookies. Sabor cremoso a sorbete de frutas con efecto potente y relajante. Base genética del Gelato.'),
('Bruce Banner #3', 'hybrid', '24-30%', '0.1-0.2%', 60, 70, 'medium', '450-550 g/m²', 'Una de las cepas más potentes del mundo con THC extremo. Cruce de OG Kush y Strawberry Diesel con efecto eufórico y potente.'),
('Strawberry Cough', 'sativa', '17-23%', '0.1-0.2%', 63, 70, 'medium', '350-450 g/m²', 'Famosa por su sabor dulce a fresa y su humo que provoca tos. Efecto cerebral claro y estimulante, ideal contra la ansiedad social.'),
('Tangie', 'sativa', '19-22%', '0.1-0.2%', 63, 70, 'medium', '400-500 g/m²', 'Remake moderna de Tangerine Dream. Aroma intenso a mandarina y cítricos. Efecto creativo y motivador, popular entre artistas.'),
('Lemon Haze', 'sativa', '17-22%', '0.1-0.2%', 63, 70, 'medium', '400-500 g/m²', 'Cruce de Silver Haze y Lemon Skunk. Aroma y sabor intenso a limón fresco. Efecto energizante y cerebral con sensación de bienestar.'),
('Maui Wowie', 'sativa', '13-19%', '0.1-0.3%', 63, 77, 'medium', '350-400 g/m²', 'Sativa tropical originaria de las islas de Hawái. Sabor a piña y cítricos tropicales con efecto energizante y creativo.'),
('Green Crack', 'sativa', '17-24%', '0.1-0.2%', 49, 56, 'easy', '450-550 g/m²', 'Nombrada por Snoop Dogg por su energía intensa. Sabor a mango tropical con efecto mental enfocado y productivo. Floración rápida.'),
('White Rhino', 'indica', '18-22%', '0.1-0.3%', 56, 63, 'easy', '450-550 g/m²', 'Variante de White Widow con dominancia índica. Producción muy alta con cogollos densos y resinosos. Efecto relajante y medicinal.'),
('Super Lemon Haze', 'sativa', '19-25%', '0.1-0.2%', 63, 70, 'medium', '500-600 g/m²', 'Doble ganadora de la Cannabis Cup. Cruce de Lemon Skunk y Super Silver Haze con sabor cítrico vibrante y efecto energizante.'),
('GDP x OG Kush', 'indica', '20-25%', '0.1-0.2%', 56, 65, 'medium', '400-500 g/m²', 'Cruce potente de dos leyendas. Combina los colores púrpura del GDP con la potencia del OG Kush. Efecto sedante y medicinal.'),
('Ice Cream Cake', 'indica', '20-25%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Wedding Cake y Gelato #33. Sabor cremoso a vainilla y masa dulce. Efecto relajante profundo ideal para insomnio.'),
('Biscotti', 'indica', '21-25%', '0.1-0.2%', 56, 63, 'medium', '350-450 g/m²', 'Cruce de Gelato #25 y South Florida OG. Sabor a galleta con notas de almendra y especias. Cogollos compactos con alta producción de resina.'),
('MAC (Miracle Alien Cookies)', 'hybrid', '20-24%', '0.1-0.2%', 60, 70, 'medium', '400-500 g/m²', 'Cruce de Alien Cookies, Starfighter y Columbian. Aroma floral y cítrico con efecto equilibrado y creativo. Tricomas abundantes.'),
('Slurricane', 'indica', '20-28%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Do-Si-Dos y Purple Punch por In House Genetics. Sabor dulce tropical con efecto sedante potente y relajación total.'),
('Cereal Milk', 'hybrid', '19-23%', '0.1-0.2%', 56, 65, 'medium', '400-450 g/m²', 'Cruce de Y Life y Snowman por Cookies. Sabor dulce cremoso como leche con cereal. Efecto equilibrado y relajante con euforia suave.'),
('Gary Payton', 'hybrid', '20-25%', '0.1-0.2%', 56, 65, 'hard', '350-400 g/m²', 'Colaboración entre Cookies y Powerzzzup Genetics. Aroma dulce y gaseoso con efecto estimulante y social. Muy exclusiva y demandada.'),
('Jealousy', 'hybrid', '22-28%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Gelato #41 y Sherbet por Seed Junky. Sabor afrutado cremoso con efecto potente y equilibrado. Tendencia a colores púrpura.'),
('London Pound Cake', 'indica', '20-25%', '0.1-0.2%', 56, 65, 'medium', '350-450 g/m²', 'Cepa premium de Cookies Fam con sabor dulce a bizcocho y bayas. Efecto relajante con bienestar mental y físico.'),
('Peanut Butter Breath', 'hybrid', '18-24%', '0.1-0.2%', 60, 70, 'medium', '350-450 g/m²', 'Cruce de Do-Si-Dos y Mendo Breath por ThugPug Genetics. Sabor único a mantequilla de maní con efecto relajante y sedante.'),
('Tropicana Cookies', 'sativa', '19-24%', '0.1-0.2%', 63, 70, 'medium', '350-450 g/m²', 'Cruce de Tangie y GSC. Aroma vibrante a naranja y frutas tropicales con colores púrpura oscuro. Efecto energizante y creativo.'),
('Forbidden Fruit', 'indica', '17-23%', '0.1-0.2%', 56, 63, 'easy', '400-500 g/m²', 'Cruce de Cherry Pie y Tangie. Aroma exótico a frutas tropicales prohibidas. Efecto relajante y tranquilo con colores vibrantes.'),
('Kush Mintz', 'hybrid', '22-27%', '0.1-0.2%', 56, 65, 'medium', '400-500 g/m²', 'Cruce de Animal Mints y Bubba Kush. Sabor refrescante a menta y kush. Efecto potente con relajación corporal profunda.'),
('Apple Fritter', 'hybrid', '22-28%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Sour Apple y Animal Cookies. Sabor dulce a manzana y canela. Efecto potente y equilibrado, ganadora de la High Times.'),
('Critical Mass', 'indica', '14-20%', '0.5-1.5%', 49, 56, 'easy', '550-650 g/m²', 'Versión mejorada de Big Bud. Producción masiva de cogollos que pueden romper las ramas. Efecto relajante suave, ideal para cultivadores comerciales.'),
('Big Bud', 'indica', '15-20%', '0.1-0.3%', 49, 63, 'easy', '500-600 g/m²', 'Nombrada por sus cogollos enormes y producción masiva. Genética afgana con efecto relajante suave. Favorita de cultivadores comerciales.'),
('Colombian Gold', 'sativa', '12-20%', '0.1-0.5%', 70, 84, 'hard', '300-400 g/m²', 'Landrace colombiana legendaria de la Sierra Nevada de Santa Marta. Aroma cítrico y terroso con efecto cerebral y energizante. Base genética histórica.'),
('Punto Rojo', 'sativa', '10-18%', '0.1-0.5%', 77, 91, 'hard', '250-350 g/m²', 'Landrace colombiana nombrada por los pistilos rojos en sus cogollos. Sativa pura tropical con efecto cerebral claro y energizante.'),
('Acapulco Gold', 'sativa', '15-23%', '0.1-0.3%', 63, 77, 'hard', '350-450 g/m²', 'Legendaria sativa mexicana considerada una de las mejores del mundo. Cogollos dorados con aroma dulce quemado y efecto cerebral eufórico.'),
('Lamb''s Bread', 'sativa', '16-21%', '0.1-0.3%', 63, 77, 'medium', '350-400 g/m²', 'Sativa jamaicana legendaria, supuestamente favorita de Bob Marley. Cogollos pegajosos y brillantes con efecto cerebral positivo y energizante.'),
('Panama Red', 'sativa', '10-16%', '0.1-0.5%', 77, 91, 'hard', '250-350 g/m²', 'Sativa centroamericana icónica de los años 60-70. Pistilos rojizos y efecto cerebral psicodélico de larga duración. Floración muy lenta.'),
('Santa Marta Gold', 'sativa', '12-18%', '0.1-0.5%', 70, 84, 'hard', '300-400 g/m²', 'Landrace colombiana de la Sierra Nevada con tonos dorados. Primo del Colombian Gold con efecto cerebral puro y lúcido.'),
('Manga Rosa', 'sativa', '11-17%', '0.1-0.5%', 70, 84, 'hard', '250-350 g/m²', 'Landrace brasileña con aroma dulce a mango rosa. Sativa tropical pura con efecto cerebral creativo y eufórico. Muy apreciada en Sudamérica.'),
('Crispy (Paraguay)', 'sativa', '8-15%', '0.2-0.5%', 63, 77, 'easy', '300-400 g/m²', 'Variedad sudamericana popular en el Cono Sur. Planta resistente y adaptable a climas variados con efecto suave y funcional.'),
('Royal Queen Seeds - Royal Gorilla', 'hybrid', '24-27%', '0.1-0.2%', 56, 63, 'medium', '500-550 g/m²', 'Versión europea del Gorilla Glue con THC extremadamente alto. Producción masiva de resina con efecto potente y duradero.'),
('Autoflowering Northern Lights', 'auto', '14-18%', '0.1-0.3%', 56, 70, 'easy', '350-450 g/m²', 'Versión autofloreciente de la clásica Northern Lights. Ideal para principiantes con ciclo completo de semilla a cosecha en 10 semanas.'),
('Auto Blueberry', 'auto', '14-20%', '0.1-0.2%', 56, 70, 'easy', '350-400 g/m²', 'Versión automática de la legendaria Blueberry. Mantiene el sabor dulce a arándano con colores azulados en un formato compacto y rápido.'),
('Auto White Widow', 'auto', '14-18%', '0.1-0.2%', 56, 70, 'easy', '300-400 g/m²', 'White Widow en formato autofloreciente. Conserva la producción de tricomas blancos y efecto equilibrado con ciclo de vida rápido.'),
('Auto Gorilla Glue', 'auto', '18-24%', '0.1-0.2%', 63, 77, 'easy', '400-500 g/m²', 'Versión autofloreciente del potente GG4. Alta producción de resina con THC elevado para una autofloreciente. Robusta y productiva.'),
('Auto Girl Scout Cookies', 'auto', '17-22%', '0.1-0.2%', 63, 77, 'medium', '350-450 g/m²', 'GSC en formato automático. Mantiene el sabor dulce y terroso con buena potencia para ser auto. Plantas compactas con cogollos resinosos.'),
('Auto Amnesia Haze', 'auto', '16-21%', '0.1-0.2%', 70, 84, 'medium', '400-500 g/m²', 'Amnesia Haze autofloreciente que conserva el efecto cerebral potente. Más alta que otras autos, necesita algo más de tiempo pero vale la pena.'),
('Auto Critical', 'auto', '14-18%', '0.3-0.8%', 49, 63, 'easy', '400-500 g/m²', 'Autofloreciente con genética Critical. Producción muy generosa para su tamaño compacto. Floración ultra rápida, ideal para cosechas continuas.'),
('Auto AK-47', 'auto', '15-20%', '0.1-0.5%', 56, 70, 'easy', '350-450 g/m²', 'Versión automática de la multipremiada AK-47. Efecto potente y duradero en formato compacto con buena producción para principiantes.'),
('Auto Jack Herer', 'auto', '15-20%', '0.1-0.2%', 63, 77, 'easy', '350-450 g/m²', 'Jack Herer en formato autofloreciente. Mantiene el efecto cerebral creativo con sabor a pino y especias en planta compacta y manejable.'),
('Auto Gelato', 'auto', '18-23%', '0.1-0.2%', 63, 77, 'medium', '400-500 g/m²', 'Gelato autofloreciente con sabor cremoso dulce y colores púrpura. THC alto para una auto con efecto equilibrado e intenso.'),
('Auto Zkittlez', 'auto', '16-22%', '0.1-0.2%', 63, 70, 'easy', '400-500 g/m²', 'Zkittlez en formato automático. Conserva el perfil de terpenos dulce frutal con producción generosa. Colores vibrantes y fácil de cultivar.'),
('Auto Runtz', 'auto', '17-23%', '0.1-0.2%', 63, 77, 'medium', '350-450 g/m²', 'Versión autofloreciente de la famosa Runtz. Sabor dulce a caramelo frutal con buenos niveles de THC y cogollos coloridos compactos.'),
('Charlotte''s Web', 'hybrid', '0.3-1%', '17-20%', 63, 77, 'medium', '350-400 g/m²', 'La cepa CBD más famosa del mundo, creada para tratar epilepsia infantil. Muy bajo THC con CBD muy alto. Revolucionó el movimiento CBD global.'),
('ACDC', 'hybrid', '1-5%', '14-20%', 63, 70, 'medium', '350-450 g/m²', 'Fenotipo CBD de Cannatonic con ratio CBD:THC de hasta 20:1. Sin efecto psicoactivo significativo, ideal para uso terapéutico diario.'),
('Cannatonic', 'hybrid', '3-6%', '6-17%', 56, 63, 'medium', '400-500 g/m²', 'Pionera del movimiento CBD con ratio equilibrado. Cruce de MK Ultra y G13 Haze. Efecto suave y medicinal sin intoxicación fuerte.'),
('Harlequin', 'sativa', '4-7%', '8-15%', 56, 65, 'medium', '350-450 g/m²', 'Sativa rica en CBD con ratio CBD:THC de 5:2. Efecto claro y funcional sin sedación. Popular para aliviar dolor y ansiedad sin colocón.'),
('Ringo''s Gift', 'hybrid', '1-5%', '10-15%', 56, 63, 'medium', '400-450 g/m²', 'Nombrada en honor a Lawrence Ringo, pionero del CBD. Cruce de ACDC y Harle-Tsu. Múltiples fenotipos con ratios CBD:THC de hasta 24:1.'),
('Remedy', 'indica', '0.5-1%', '12-16%', 56, 63, 'easy', '350-450 g/m²', 'Índica CBD pura prácticamente sin THC. Ideal para quienes buscan beneficios terapéuticos sin ningún efecto psicoactivo.'),
('Sour Tsunami', 'hybrid', '1-4%', '10-13%', 56, 65, 'medium', '350-400 g/m²', 'Una de las primeras cepas criadas específicamente para alto CBD. Cruce de Sour Diesel y NYC Diesel. Efecto claro y medicinal.'),
('Pennywise', 'indica', '8-12%', '8-12%', 56, 63, 'easy', '400-500 g/m²', 'Cruce de Harlequin y Jack the Ripper con ratio THC:CBD de 1:1. Efecto suave y medicinal, ideal para principiantes en cannabis terapéutico.'),
('Stephen Hawking Kush', 'indica', '1-5%', '10-15%', 56, 63, 'easy', '400-450 g/m²', 'Índica rica en CBD con efecto relajante sin intoxicación. Sabor a menta y bayas. Ideal para aliviar dolor y espasmos musculares.'),
('CBD Critical Mass', 'indica', '4-7%', '7-10%', 49, 56, 'easy', '500-600 g/m²', 'Versión CBD de la productiva Critical Mass. Ratio THC:CBD equilibrado con producción masiva. Efecto suave y relajante medicinal.'),
('Dinamed CBD Plus', 'hybrid', '0.5-1%', '14-20%', 56, 63, 'easy', '400-500 g/m²', 'Cepa CBD de Dinafem con THC casi inexistente. CBD extremadamente alto con efecto nulo de intoxicación. Ideal para uso terapéutico puro.'),
('Sweet and Sour Widow', 'indica', '4-8%', '4-8%', 56, 63, 'easy', '350-450 g/m²', 'Versión CBD de White Widow con ratio 1:1. Sabor dulce y ácido con efecto suave y equilibrado. Buena para microdosificación.'),
('Afghani', 'indica', '15-20%', '0.1-0.5%', 49, 56, 'easy', '400-500 g/m²', 'Landrace afgana pura, base genética de innumerables índicas modernas. Alta producción de resina ideal para hashish. Efecto sedante y corporal.'),
('Thai Stick', 'sativa', '15-22%', '0.1-0.3%', 70, 91, 'hard', '300-400 g/m²', 'Sativa landrace tailandesa, una de las más antiguas del mundo. Efecto cerebral psicodélico intenso. Tradicionalmente atada a palos de bambú.'),
('Malawi Gold', 'sativa', '14-20%', '0.1-0.3%', 84, 105, 'hard', '300-400 g/m²', 'Sativa pura africana de Malawi con floración muy larga. Cogollos enormes con efecto cerebral claro y energizante. Para cultivadores expertos.'),
('Headband', 'hybrid', '20-27%', '0.1-0.3%', 63, 70, 'medium', '400-500 g/m²', 'Cruce de OG Kush y Sour Diesel. Nombrada por la sensación de presión alrededor de la cabeza. Efecto potente y duradero con sabor a limón y diésel.'),
('Cherry Pie', 'hybrid', '16-24%', '0.1-0.2%', 56, 63, 'medium', '400-450 g/m²', 'Cruce de Granddaddy Purple y Durban Poison. Aroma dulce a cereza y tarta con efecto relajante y eufórico equilibrado.'),
('Platinum OG', 'indica', '18-24%', '0.1-0.2%', 56, 63, 'medium', '350-450 g/m²', 'Variante premium de OG Kush con THC elevado. Cogollos con brillo platinado de tricomas. Efecto sedante potente ideal para dolor crónico.'),
('LA Confidential', 'indica', '19-25%', '0.1-0.3%', 49, 56, 'easy', '400-500 g/m²', 'Índica pura de Los Ángeles. Aroma a pino y terroso con efecto psicodélico inicial que evoluciona a relajación profunda. Floración rápida.'),
('Skywalker OG', 'indica', '20-26%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Skywalker y OG Kush. Aroma a pino, especias y combustible. Efecto potente de cuerpo completo ideal para insomnio y dolor.'),
('Banana Kush', 'hybrid', '18-25%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Ghost OG y Skunk Haze. Aroma tropical dulce a banana con efecto relajante y feliz. Popular en la costa oeste de EE.UU.'),
('King Louis XIII', 'indica', '20-26%', '0.1-0.2%', 56, 63, 'medium', '350-450 g/m²', 'Variedad OG de élite con aroma potente a pino y terroso. Efecto índica pesado con sedación profunda. Favorita en dispensarios californianos.'),
('Auto Purple Punch', 'auto', '15-20%', '0.1-0.2%', 56, 70, 'easy', '400-450 g/m²', 'Versión autofloreciente de Purple Punch. Mantiene los colores púrpura y sabor a uva en formato compacto. Ideal para espacios reducidos.'),
('Auto Wedding Cake', 'auto', '18-23%', '0.1-0.2%', 63, 77, 'medium', '400-500 g/m²', 'Wedding Cake en formato autofloreciente con alta potencia. Sabor cremoso a vainilla con cogollos densos y resinosos en 10-11 semanas.'),
('CBD Auto Compassion Lime', 'auto', '5-7%', '7-10%', 63, 77, 'easy', '350-400 g/m²', 'Autofloreciente CBD de Dutch Passion con ratio 1:1. Sabor cítrico a lima con efecto suave y medicinal. Perfecta para uso terapéutico automático.'),
('Mango Kush', 'hybrid', '16-20%', '0.3-0.5%', 56, 65, 'easy', '400-450 g/m²', 'Cruce de Mango y Hindu Kush con aroma tropical a mango maduro. Efecto relajante y alegre. Planta resistente y fácil para principiantes.'),
('Chocolate Thai', 'sativa', '12-18%', '0.1-0.3%', 70, 84, 'hard', '300-350 g/m²', 'Landrace tailandesa con aroma dulce a chocolate y café. Efecto cerebral energético y meditativo. Genética base de muchas cepas modernas.'),
('Original Glue (GG)', 'hybrid', '24-28%', '0.1-0.2%', 56, 63, 'medium', '450-550 g/m²', 'La original Gorilla Glue, cruce accidental de Chem Sis, Sour Dubb y Chocolate Diesel. Resina extrema que pega las tijeras al podar.'),
('Obama Runtz', 'hybrid', '20-26%', '0.1-0.2%', 56, 65, 'medium', '400-450 g/m²', 'Cruce de Runtz y Afghani con sabor dulce y afrutado. Cogollos púrpura densos con efecto relajante potente. Muy demandada en el mercado actual.'),
('Gelonade', 'hybrid', '20-25%', '0.1-0.2%', 56, 63, 'medium', '400-500 g/m²', 'Cruce de Gelato #41 y Lemon Tree. Perfil terpénico cítrico cremoso único. Efecto energizante y cerebral con potencia elevada.'),
('Auto CBD Northern Lights', 'auto', '1-3%', '12-16%', 63, 77, 'easy', '350-400 g/m²', 'Northern Lights CBD en formato automático. Muy bajo THC con alto CBD en planta compacta y rápida. Perfecta para cultivo terapéutico discreto.')
ON CONFLICT (name) DO NOTHING;
